"""Códigos de eventos de auditoría compartidos entre apps.

Mantener estos literales centralizados evita que las vistas de dominio importen
el modelo AuditLog directamente solo para acceder a sus choices.
"""

EVENTO_ENTRADA = "ENTRADA"
EVENTO_SALIDA = "SALIDA"
EVENTO_AJUSTE = "AJUSTE"
EVENTO_LOGIN_OK = "LOGIN_OK"
EVENTO_LOGIN_FAIL = "LOGIN_FAIL"
EVENTO_PASSWORD_RESET = "PASSWORD_RESET"
EVENTO_PASSWORD_CHANGED = "PASSWORD_CHANGED"
EVENTO_USUARIO_CREADO = "USUARIO_CREADO"
EVENTO_USUARIO_DESACTIVADO = "USUARIO_DESACTIVADO"
EVENTO_PERMISO_CAMBIADO = "PERMISO_CAMBIADO"
EVENTO_EXPORTACION = "EXPORTACION"
EVENTO_EXPORTACION_PRODUCTOS = "EXPORTACION_PRODUCTOS"
EVENTO_EXPORTACION_MOVIMIENTOS = "EXPORTACION_MOVIMIENTOS"
EVENTO_FACTURA_SUBIDA = "FACTURA_SUBIDA"
EVENTO_FACTURA_DESCARGADA = "FACTURA_DESCARGADA"
EVENTO_SYNC_CRM = "SYNC_CRM"
EVENTO_ALERTA_RESUELTA = "ALERTA_RESUELTA"
