# Generated by Django 4.2.30 on 2026-08-06 18:11

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0005_producto_vin'),
        ('clientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=30, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('esquema', models.CharField(choices=[('CONTADO', 'Contado'), ('CREDITO', 'Crédito'), ('ARRENDAMIENTO', 'Arrendamiento')], default='CONTADO', max_length=20)),
                ('estado', models.CharField(choices=[('ENVIADA', 'Enviada'), ('GANADA', 'Ganada'), ('PERDIDA', 'Perdida')], default='ENVIADA', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='clientes.cliente')),
                ('unidad_interes', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to='inventario.producto', verbose_name='Unidad de interés')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cotizaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cotización',
                'verbose_name_plural': 'cotizaciones',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', '-created_at'], name='cotizacione_cliente_f6fd48_idx'), models.Index(fields=['estado', '-created_at'], name='cotizacione_estado_842622_idx')],
            },
        ),
    ]
