# Generated by Django 4.2.30 on 2026-06-02 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('config', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'configuración de dashboard',
                'verbose_name_plural': 'configuraciones de dashboard',
            },
        ),
        migrations.CreateModel(
            name='ReporteProgramado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('EXCEL', 'Excel'), ('PDF', 'PDF'), ('CSV', 'CSV')], max_length=50)),
                ('cron_expresion', models.CharField(max_length=100)),
                ('destinatarios', models.JSONField(default=list)),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'reporte programado',
                'verbose_name_plural': 'reportes programados',
            },
        ),
    ]
