# Generated by Django 4.2.30 on 2026-08-04 17:57

from django.db import migrations, models

import apps.metricas.models


class Migration(migrations.Migration):
    dependencies = [
        ("metricas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reporteprogramado",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="dashboardconfig",
            name="config",
            field=models.JSONField(default=apps.metricas.models.empty_dict),
        ),
        migrations.AlterField(
            model_name="reporteprogramado",
            name="cron_expresion",
            field=models.CharField(
                help_text="Expresión cron estándar (5 campos: min hora día_mes mes día_semana)", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="reporteprogramado",
            name="destinatarios",
            field=models.JSONField(default=apps.metricas.models.empty_list, help_text="Lista de emails"),
        ),
    ]
