# Generated by Django 4.2.30 on 2026-08-06 18:11

import uuid

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('rfc', models.CharField(blank=True, max_length=13, validators=[django.core.validators.RegexValidator('^[A-ZÑ&0-9]{12,13}$', 'RFC inválido')])),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'cliente',
                'verbose_name_plural': 'clientes',
                'ordering': ['empresa', 'nombre'],
                'indexes': [models.Index(fields=['email'], name='clientes_cl_email_eae461_idx'), models.Index(fields=['rfc'], name='clientes_cl_rfc_3080e6_idx')],
            },
        ),
    ]
