# Generated by Django 4.2.30 on 2026-07-27 18:06

import uuid
from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.finanzas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0003_movimiento_inventario__product_b6c1a5_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('proveedor_cliente', models.CharField(blank=True, max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha', models.DateField()),
                ('archivo', models.FileField(help_text='PDF o XML de la factura', upload_to=apps.finanzas.models.upload_factura_path)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='inventario.movimiento')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'factura',
                'verbose_name_plural': 'facturas',
                'ordering': ['-fecha', '-created_at'],
                'indexes': [models.Index(fields=['tipo', '-fecha'], name='finanzas_fa_tipo_3c2fa2_idx'), models.Index(fields=['fecha'], name='finanzas_fa_fecha_8f4ecd_idx')],
            },
        ),
    ]
