# Generated by Django 4.2.30 on 2026-08-04 17:57

import django.core.validators
from django.db import migrations, models

import apps.finanzas.models


class Migration(migrations.Migration):
    dependencies = [
        ("finanzas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="factura",
            name="archivo",
            field=models.FileField(
                help_text="PDF o XML de la factura",
                upload_to=apps.finanzas.models.upload_factura_path,
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=["pdf", "xml"])],
            ),
        ),
    ]
