# Generated by Django 4.2.30 on 2026-07-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['producto', 'almacen', '-created_at'], name='inventario__product_b6c1a5_idx'),
        ),
        migrations.AddIndex(
            model_name='movimiento',
            index=models.Index(fields=['tipo', '-created_at'], name='inventario__tipo_f73401_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['producto', 'almacen'], name='inventario__product_4ec690_idx'),
        ),
    ]
