# Generated by Django 4.2.30 on 2026-07-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_movimiento_inventario__product_b6c1a5_idx_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(check=models.Q(('cantidad__gte', 0)), name='stock_no_negativo'),
        ),
    ]
