# Generated by Django 4.2.30 on 2026-08-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_stock_stock_no_negativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='vin',
            field=models.CharField(blank=True, help_text='Número de chasis/VIN para unidades (tractocamiones, remolques)', max_length=17),
        ),
    ]
