# Generated by Django 4.2.30 on 2026-06-02 19:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENVIADO', 'Enviado'), ('FALLIDO', 'Fallido')], default='PENDIENTE', max_length=20)),
                ('payload', models.JSONField()),
                ('respuesta', models.JSONField(blank=True, null=True)),
                ('intentos', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'log de sincronización',
                'verbose_name_plural': 'logs de sincronización',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebhookCRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('evento', models.CharField(max_length=50)),
                ('url_destino', models.URLField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'webhook CRM',
                'verbose_name_plural': 'webhooks CRM',
            },
        ),
    ]
