# Generated by Django 4.2.30 on 2026-07-07 16:53

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaveCRM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('clave_publica', models.CharField(max_length=64, unique=True, verbose_name='identificador público de la clave')),
                ('hash_clave', models.CharField(max_length=128, verbose_name='SHA-256 del secreto')),
                ('activa', models.BooleanField(default=True, verbose_name='clave en uso actualmente')),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField(verbose_name='fecha de expiración')),
                ('rotada_en', models.DateTimeField(blank=True, null=True, verbose_name='fecha en que fue rotada')),
            ],
            options={
                'verbose_name': 'clave CRM',
                'verbose_name_plural': 'claves CRM',
                'ordering': ['-creada_en'],
            },
        ),
    ]
