# Generated by Django 4.2.30 on 2026-06-02 19:10

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('evento', models.CharField(choices=[('ENTRADA', 'Entrada de inventario'), ('SALIDA', 'Salida de inventario'), ('AJUSTE', 'Ajuste / merma'), ('LOGIN_OK', 'Inicio de sesión exitoso'), ('LOGIN_FAIL', 'Intento de sesión fallido'), ('PASSWORD_RESET', 'Recuperación de contraseña'), ('PASSWORD_CHANGED', 'Contraseña cambiada'), ('USUARIO_CREADO', 'Usuario creado'), ('USUARIO_DESACTIVADO', 'Usuario desactivado'), ('PERMISO_CAMBIADO', 'Permiso modificado'), ('EXPORTACION', 'Exportación de datos'), ('SYNC_CRM', 'Sincronización con CRM')], max_length=30)),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('datos', models.JSONField()),
                ('hash_previo', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'registro de auditoría',
                'verbose_name_plural': 'registros de auditoría',
                'ordering': ['-timestamp'],
            },
        ),
    ]
