# Generated by Django 4.2.30 on 2026-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auditoria", "0003_apply_auditlog_revoke"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["evento", "-timestamp"], name="auditoria_a_evento_1f676b_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["usuario", "-timestamp"], name="auditoria_a_usuario_bf6aef_idx"),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(fields=["ip_address", "-timestamp"], name="auditoria_a_ip_addr_7cb21b_idx"),
        ),
    ]
